-- Exécution recommandée dans l'éditeur SQL Supabase (dans cet ordre):
-- 1) 001_extensions_and_types.sql
-- 2) 002_create_tables.sql
-- 3) 003_rls_policies.sql
-- 4) 004_views_and_helpers.sql
--
-- Stockage des contrats:
-- - Créez un bucket Storage nommé 'contracts' dans Supabase (Storage > Create bucket).
-- - Chargez les PDF/documents dans ce bucket et enregistrez storage_path + file_name dans public.prospect_contracts.
--
-- Remarques de modélisation:
-- - Aucune colonne de CA n'est incluse (contrats de service). Utilisez suivi_statut/suivi_score pour l'indicateur de suivi.
-- - Le suivi du volume est géré via la table public.teleconsultations (événements unitaires ou agrégés via 'count').
-- - Ajustez les politiques RLS selon vos rôles/équipes. Celles livrées ouvrent l'accès aux utilisateurs authentifiés.
